.n64

GetStringWidth equ 0x800902cc
//u32 GetStringWidth(char *str, u32 strlen, bool variableWidth)
GetCharLength equ 0x8009034c
//u8 GetCharLength(char *currChar)
GetCharLenFromMsgPos equ 0x800903a8
//u8 GetCharLenFromMsgPos(u8 *loadedMessage, u8 currPos)
FillStringWithChar equ 0x8009992c
//u32 FillStringWithChar(char *target, u8 length, char character)
GetStrLenNoWhiteSpace equ 0x8009e8d0
//u32 GetStrLenNoWhiteSpace(char *string, u32 length)
